include:
  - board: nice_nano_v2
    shield: n36tsu_left nice_view
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: n36tsu_right nice_view
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset
